### ISSUE TITLE
How to configure Vite?

### ISSUE THREAD

**Issue by nichoth** [Level/browser-level#13]
Tried the example in README —

```js
const { BrowserLevel } = require('browser-level')

// Create a database called 'example'
const db = new BrowserLevel('example', { valueEncoding: 'json' })
```

Got an error:

> Uncaught TypeError: Class extends value undefined is not a constructor or null

<img width="584" alt="image" src="https://github.com/Level/browser-level/assets/5776508/0d42b1c9-a558-4df5-b01f-1c4bfc6d1125">

This is using `vite` to bundle some code with ESM `import` statements.

**Comment by jacoscaz** [comment]
@nichoth try installing the userland `events` module from NPM, possibly along with `@types/events`.

**Comment by nichoth** [comment]
Thanks; installing `events` has fixed.
