### ISSUE TITLE
Timeline for V2

### ISSUE THREAD

**Issue by jacoscaz** [Level/browser-level#14]
Hi! Is there any timeframe for the upgrade of this package to `abstract-level@2.x`, such as what recently happened with `classic-level` and `memory-level`?

This is by no means an attempt to pressure anyone into any kind of commitment nor a request for anyone to put in the necessary work. I'm simply wondering whether the upgrade is already in someone's todo list or whether it's still up for grab with no known plan to work on it for the foreseeable future.

Thanks again for all the wonderful work @vweevers and all maintainers!

**Comment by vweevers** [comment]
I started on it a while back but I ended up yak shaving (e.g. fixing bugs in the test runner rather than any code here) and that messed with my motivation. I'll get back on that horse (or yak) in December. Shouldn't take long.

**Comment by jacoscaz** [comment]
@vweevers thank you for both the fast feedback and for taking on V2! I was about to close this issue but then figured it might be useful to others looking for the same thing. Feel free to close it, though, if you believe otherwise.

Once again, no rush meant or implied. As a downstream consumer, I'm very grateful for all the work happening in the `/Level` organization.

**Comment by vweevers** [comment]
Released [2.0.0](https://github.com/Level/browser-level/releases/tag/v2.0.0).

**Comment by jacoscaz** [comment]
Upgrading on my end turned out to be much much much simpler than expected. Performance not only did not worsen but actually improved slightly! Thanks again @vweevers!
