### ISSUE TITLE
Can run with ESM bundler like ViteJS?

### ISSUE THREAD

**Issue by bitburnerz** [Level/browser-level#4]
Does browser-level only work with CommonJS bundlers like Browserify or can I use something like ViteJS? So far I've had no success so I'm just curious if I'm missing anything.

**Comment by vweevers** [comment]
As long as the bundler converts CommonJS modules, it should work. I don't know about Vite, but check out this webpack example for comparison: https://github.com/Level/webpack-starter.

With Vite/Rollup you may need something like https://github.com/FredKSchott/rollup-plugin-polyfill-node for `events`.

**Comment by bitburnerz** [comment]
I noticed webpack-starter is using "level" instead of "browser-level". I tried changing that but then could not get it to compile anymore. Is there something wrong with my approach?

**Comment by vweevers** [comment]
`level` is a convenience package without any code of itself. It exports `classic-level` in Node.js, or `browser-level` in browsers (if the bundler respects the [`browser`](https://github.com/Level/level/blob/c3068d266dcfe6057e46aeaa52823cc827cbdc0f/package.json#L20) field). If you're only targeting browsers, then `browser-level` is all you need.

**Comment by bitburnerz** [comment]
Ok. I managed to get _webpack-starter_ to work with `browser-level` directly. Thank you!
