### ISSUE TITLE
This package is broken

### ISSUE THREAD

**Issue by cow1337killer3** [Level/browser-level#9]
const req = indexedDB.open(this[kNamePrefix] + this[kLocation], this[kVersion])
                ^

ReferenceError: indexedDB is not defined
    at BrowserLevel._open (\node_modules\browser-level\index.js:77:17)
    at BrowserLevel.open (\node_modules\abstract-level\abstract-level.js:153:12)
    at \node_modules\abstract-level\abstract-level.js:102:14
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by vweevers** [comment]
It's meant to be used in a browser, where `indexedDB` is a global.

**Comment by alex-r-bigelow** [comment]
Just a note for anyone trying to figure out how to incorporate `browser-level`-dependent code in unit tests, this can usually be fixed with something like:

```
// vitest.setup.ts

import { indexedDB } from 'fake-indexeddb';

globalThis.indexedDB = indexedDB;
```
